-- Snowflake Snowsight Worksheet
-- Purpose: Environment setup for Geo Performance lab
-- Warehouse: MY_WH (update if different)

CREATE DATABASE IF NOT EXISTS GEOLAB;

CREATE OR REPLACE SCHEMA GEOLAB.PERFORMANCE;

USE DATABASE GEOLAB;
USE SCHEMA PERFORMANCE;

USE WAREHOUSE MY_WH;

ALTER SESSION SET GEOGRAPHY_OUTPUT_FORMAT = 'WKT';
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

SHOW DATABASES;
